name: Java CI with Gradle

on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]

jobs:
  build-docker-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew    

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Start MySQL container for Gradle build
      run: |
         sudo docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=test -p 3306:3306 -d mysql:8
         sleep 30

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # Docker 이미지 Build
    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/usinsa .

    # DockerHub Login (push 하기 위해)
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Docker hub 로 push
    - name: Docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/usinsa

    # 위 과정에서 푸시한 이미지를 ec2에서 풀받아서 실행
  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
    - name: docker pull
      run : sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/usinsa

    - name: docker stop container
      run: |
        if [ $(sudo docker ps -a -q -f name=usinsa) ]; then
          sudo docker stop usinsa
        fi

    - name: docker run new container
      run: sudo docker run --rm -it -d -p 80:8080 --name usinsa ${{ secrets.DOCKERHUB_USERNAME }}/usinsa

    - name: delete old docker image
      run: sudo docker system prune -f
